---
- name: Query user ID for '{{ ansible_user }}'
  ansible.builtin.getent:
    database: passwd
    key: "{{ ansible_user }}"

- name: Symmlink DCV Xauthority cookie to ~/.Xauthority
  become: true
  ansible.builtin.file:
    src:   "/run/user/{{ getent_passwd[ansible_user][1] }}/dcv/{{ ansible_user }}.xauth"
    dest:  "{{ ansible_env.HOME }}/.Xauthority"
    state: link
    force: true # Xauthority may not exist yet but will be created by an X session
    follow: false
